import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {weeklyModel, outcomeFor, weeklyTakeaway, OUTCOMES, PATTERNS} from '../public-data.js';
const read=p=>JSON.parse(fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'));
const release=read('data/releases/current.json');
const relationship=read('data/symbiosis/current.json');
function fixture(outcomes=['benefit_shown','downside_shown','benefit_and_downside','no_clear_people_change','too_little_evidence']) {
 const r={release_id:'2027-W03',period_start:'2027-01-18',period_end:'2027-01-24',content_sha256:'fixture',counts:{ai_relevant_articles:outcomes.length+2,ai_relevant_event_records:outcomes.length,new_event_records:outcomes.length},evidence:outcomes.map((_,i)=>({event_id:String(i)}))};
 const s={release_id:r.release_id,period_start:r.period_start,period_end:r.period_end,source_release_sha256:'fixture',people_signals:{expected_units:outcomes.length,classified_units:outcomes.length},evidence:outcomes.map((o,i)=>({event_id:String(i),public_signals:{people_gaining:['benefit_shown','benefit_and_downside'].includes(o),people_losing_ground:['downside_shown','benefit_and_downside'].includes(o)},evidence_status:o==='too_little_evidence'?'insufficient':'sufficient',evidence_basis_summary:{full_text_sources:o==='too_little_evidence'?0:1},relationship_patterns:{mutualism:o==='benefit_shown'||o==='benefit_and_downside',ai_benefiting_parasitism:o==='benefit_and_downside'}}))};return [r,s];
}
test('the current row-level breakdown reconciles to the release and published signals',{skip:relationship.public_status==='classification_in_progress'||relationship.source_release_sha256!==release.content_sha256},()=>{
 const m=weeklyModel(release,relationship);assert.equal(m.ready,true);assert.equal(Object.values(m.counts).reduce((a,b)=>a+b),m.total);
 assert.equal(m.counts.benefit_shown+m.counts.benefit_and_downside,relationship.people_signals.people_signal_counts.people_gaining);
 assert.equal(m.counts.downside_shown+m.counts.benefit_and_downside,relationship.people_signals.people_signal_counts.people_losing_ground);
 assert.equal(m.counts.too_little_evidence,relationship.people_signals.not_clear_breakdown.not_enough_evidence);
 assert.equal(m.counts.no_clear_people_change,relationship.people_signals.not_clear_breakdown.no_directional_people_change);
 for(const k of Object.keys(PATTERNS))assert.equal(m.patterns[k],relationship.people_signals.relationship_pattern_counts[k]);
});
test('a future mixed-effects week counts both exactly once and includes it in the takeaway',()=>{const m=weeklyModel(...fixture());assert.equal(m.ready,true);assert.deepEqual(Object.values(m.counts),[1,1,1,1,1]);assert.match(weeklyTakeaway(m),/1 describe both/);});
test('two-sided scope counts unique developments even when patterns overlap',()=>{const m=weeklyModel(...fixture());assert.equal(m.twoSided,2);assert.equal(m.patterns.mutualism+m.patterns.ai_benefiting_parasitism,3);});
test('legacy single-label configurations never replace explicit public pattern evidence',()=>{const [r,s]=fixture();s.event={display_configuration_counts:{mutualism:999},display_complete_configuration_count:999};const m=weeklyModel(r,s);assert.equal(m.patterns.mutualism,2);assert.equal(m.twoSided,2);});
test('absent, stale, mismatched and unfinished assessments are not fabricated as unclear',()=>{for(const change of [s=>null,s=>({...s,release_id:'old'}),s=>({...s,source_release_sha256:'old'}),s=>({...s,period_end:'2027-01-25'}),s=>({...s,evidence:s.evidence.slice(1)}),s=>({...s,people_signals:{...s.people_signals,classified_units:2}})]){const [r,s]=fixture();assert.equal(weeklyModel(r,change(s)).ready,false);}assert.equal(outcomeFor(null),null);});
test('duplicate and wrong event IDs do not pass just because the row count matches',()=>{const [r,s]=fixture();s.evidence[1].event_id=s.evidence[0].event_id;assert.equal(weeklyModel(r,s).ready,false);s.evidence[1].event_id='alien';assert.equal(weeklyModel(r,s).ready,false);});
test('string booleans and unrecognised evidence status remain pending',()=>{const [r,s]=fixture();s.evidence[0].public_signals.people_gaining='false';assert.equal(weeklyModel(r,s).ready,false);s.evidence[0].public_signals.people_gaining=true;s.evidence[0].evidence_status='pending';assert.equal(weeklyModel(r,s).ready,false);});
test('a missing body and inconclusive full text have distinct evidence counts',()=>{const [r,s]=fixture(['too_little_evidence','too_little_evidence']);s.evidence[1].evidence_basis_summary.full_text_sources=1;const m=weeklyModel(r,s);assert.equal(m.noBody,1);assert.equal(m.insufficientWithBody,1);assert.equal(m.counts.too_little_evidence,2);});
test('French, Chinese and bilingual source metadata do not change eligibility or interpretation',()=>{const [r,s]=fixture();for(const lang of ['fr','zh','en,fr']){s.evidence.forEach(x=>x.sources=[{source_language:lang}]);assert.equal(weeklyModel(r,s).ready,true);assert.equal(weeklyModel(r,s).total,5);}});
test('the historical and period totals reconcile from published records',()=>{const idx=read('data/releases/index.json');for(const w of idx.weekly){assert.equal(w.articles-w.event_records,w.extra_coverage);assert.equal(w.new_event_records+w.recurring_event_records+(w.possible_historical_match_event_records||0)+(w.unclassified_novelty_event_records||0),w.event_records);}const pi=read('data/releases/period-index.json');for(const p of pi.summaries){const d=read(p.path.replace(/^\//,''));assert.equal(d.attention.published_coverage_articles,p.articles);assert.equal(d.reality.distinct_event_records,p.distinct_event_records);}});
test('all visible weekly pages use the same model and the public build includes its assets',()=>{for(const p of ['site.js','edu/dashboard.js','report/report.js']) assert.match(fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'),/weeklyModel/);const builder=fs.readFileSync(new URL('../scripts/build_public_site.py',import.meta.url),'utf8');for(const path of ['public-data.js','editorial.css','data/geography'])assert.ok(builder.includes(path));assert.match(fs.readFileSync(new URL('../report/index.html',import.meta.url),'utf8'),/<script type="module" src="\/report\/report\.js/);});

test('insufficient evidence cannot simultaneously establish a benefit',()=>{const [r,s]=fixture();s.evidence[0].evidence_status='insufficient';assert.equal(weeklyModel(r,s).ready,false);});
test('missing release provenance does not pass as a current assessment',()=>{const [r,s]=fixture();delete s.source_release_sha256;assert.equal(weeklyModel(r,s).ready,false);});
