#!/usr/bin/env python3
"""Validate an owner-QC CSV, build apply decisions, and merge adjudicated rows into owner gold.

The CSV is generated by export_symbiosis_qc.py. Only rows with all three HUMAN
labels completed and HUMAN_include_in_gold=yes are ingested. This makes random
QC optional: a reviewer can code any subset without pretending the rest were
reviewed.
"""
from __future__ import annotations

import argparse
import csv
import json
import hashlib
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from symbiosis_common import (
    AI_ROLES,
    CODEBOOK_VERSION,
    EVIDENCE_STATUSES,
    HUMAN_TYPES,
    RELATIONSHIP_PATTERN_KEYS,
    derive_configuration,
    normalize_ai_role,
    normalize_evidence_status,
    normalize_human_type,
    normalize_relationship_patterns,
    public_signals_from_patterns,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GOLD = ROOT / "validation" / "symbiosis-owner-gold.json"
DEFAULT_DECISIONS = ROOT / "review" / "symbiosis" / "qc-decisions.json"
DEFAULT_SUMMARY = ROOT / "review" / "symbiosis" / "qc-ingest-summary.json"
DEFAULT_HISTORY = ROOT / "validation" / "symbiosis-owner-qc-history.json"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def truthy(value: Any) -> bool:
    return str(value or "").strip().casefold() in {"1", "true", "yes", "y", "include"}


def split_pipe(value: Any) -> list[str]:
    return [item.strip() for item in str(value or "").split("|") if item.strip()]


def answer(value: Any) -> str:
    raw = str(value or "").strip().casefold()
    aliases = {
        "y": "yes", "true": "yes", "1": "yes",
        "n": "no", "false": "no", "0": "no",
        "unsure": "not sure", "unclear": "not sure", "not_sure": "not sure",
    }
    return aliases.get(raw, raw)


def plain_row_labels(row: dict[str, Any], row_number: int) -> tuple[dict[str, Any] | None, list[str]]:
    """Translate the plain-language v2 workbook answers into stored labels."""
    errors: list[str] = []
    fields = {
        "enough": answer(row.get("HUMAN_enough_to_judge")),
        "people_gain": answer(row.get("HUMAN_people_gaining")),
        "people_lose": answer(row.get("HUMAN_people_losing_ground")),
        "ai_advance": answer(row.get("HUMAN_ai_advancing")),
        "ai_limited": answer(row.get("HUMAN_ai_limited")),
        "unequal": answer(row.get("HUMAN_unequal_benefits")),
    }
    if not any(fields.values()):
        return None, []
    allowed = {"yes", "no", "not sure"}
    for key, value in fields.items():
        if value not in allowed:
            errors.append(f"row {row_number}: {key} must be Yes, No, or Not sure")
    if errors:
        return None, errors
    if "not sure" in fields.values():
        errors.append(
            f"row {row_number}: resolve every Not sure answer before importing this row, or leave the row out of the import"
        )
        return None, errors

    enough = fields["enough"] == "yes"
    if not enough:
        directional = [fields[key] for key in ("people_gain", "people_lose", "ai_advance", "ai_limited")]
        if any(value == "yes" for value in directional):
            errors.append(
                f"row {row_number}: Enough to judge=No cannot be combined with a directional Yes answer"
            )
            return None, errors
        human_type = "unclear"
        ai_role = "unclear"
        evidence_status = "insufficient"
    else:
        human_gain = fields["people_gain"] == "yes"
        human_lose = fields["people_lose"] == "yes"
        ai_advance = fields["ai_advance"] == "yes"
        ai_limited = fields["ai_limited"] == "yes"
        human_type = "unclear" if human_gain and human_lose else "extension" if human_gain else "restriction" if human_lose else "neutral"
        ai_role = "unclear" if ai_advance and ai_limited else "ai_extension" if ai_advance else "ai_restriction" if ai_limited else "neutral"
        directional_sides = int(human_gain or human_lose) + int(ai_advance or ai_limited)
        internally_mixed = (human_gain and human_lose) or (ai_advance and ai_limited)
        evidence_status = "partial" if directional_sides == 1 and not internally_mixed else "sufficient"

    configuration, human_direction, ai_direction, plain_label = derive_configuration(
        human_type, ai_role, evidence_status
    )
    human_gain = fields["people_gain"] == "yes" if enough else False
    human_lose = fields["people_lose"] == "yes" if enough else False
    ai_advance = fields["ai_advance"] == "yes" if enough else False
    ai_limited = fields["ai_limited"] == "yes" if enough else False
    patterns = {
        "mutualism": human_gain and ai_advance,
        "ai_benefiting_parasitism": human_lose and ai_advance,
        "human_benefiting_parasitism": human_gain and ai_limited,
        "competition": human_lose and ai_limited,
    }
    distribution_signal = "unequal" if fields["unequal"] == "yes" else "not_shown"
    public_signals = public_signals_from_patterns(
        patterns,
        configuration=configuration,
        human_direction=human_direction,
        evidence_status=evidence_status,
        distribution_signal=distribution_signal,
    )
    return {
        "human_type": human_type,
        "ai_role": ai_role,
        "evidence_status": evidence_status,
        "configuration": configuration,
        "human_direction": human_direction,
        "ai_direction": ai_direction,
        "plain_label": plain_label,
        "relationship_patterns": patterns,
        "public_signals": public_signals,
        "distribution_signal": distribution_signal,
    }, []


def load_gold(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {
            "schema_version": "aieo_symbiosis_owner_gold_v1",
            "codebook_version": CODEBOOK_VERSION,
            "description": (
                "Owner-adjudicated relationship labels from optional quality-control samples. "
                "These rows are the highest-provenance calibration set and are distinct from legacy AI-assisted review manifests."
            ),
            "updated_at": None,
            "records": [],
        }
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("codebook_version") != CODEBOOK_VERSION:
        raise SystemExit(
            f"Owner gold codebook {payload.get('codebook_version')} does not match {CODEBOOK_VERSION}."
        )
    if not isinstance(payload.get("records"), list):
        raise SystemExit("Owner gold must contain a records array.")
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Completed QC CSV")
    parser.add_argument("--reviewer", default="Kedma Hamelberg")
    parser.add_argument("--gold-path", default=str(DEFAULT_GOLD.relative_to(ROOT)))
    parser.add_argument("--history-path", default=str(DEFAULT_HISTORY.relative_to(ROOT)))
    parser.add_argument("--decisions-output", default=str(DEFAULT_DECISIONS.relative_to(ROOT)))
    parser.add_argument("--summary-output", default=str(DEFAULT_SUMMARY.relative_to(ROOT)))
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def root_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else ROOT / path


def main() -> int:
    args = parse_args()
    input_path = root_path(args.input)
    if not input_path.exists():
        raise SystemExit(f"QC input does not exist: {input_path}")

    with input_path.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit("QC input has no rows.")

    plain_schema = "HUMAN_people_gaining" in rows[0]
    required_cols = {
        "release_id", "event_id", "unit_key", "development_title", "source_urls",
        "model_configuration", "model_evidence_status", "HUMAN_include_in_gold",
    }
    if plain_schema:
        required_cols.update({
            "HUMAN_enough_to_judge", "HUMAN_people_gaining",
            "HUMAN_people_losing_ground", "HUMAN_ai_advancing",
            "HUMAN_ai_limited", "HUMAN_unequal_benefits",
        })
    else:
        required_cols.update({
            "model_human_experience_type", "model_ai_expressive_role",
            "HUMAN_human_experience_type", "HUMAN_ai_expressive_role",
            "HUMAN_evidence_status",
        })
    missing = sorted(required_cols - set(rows[0]))
    if missing:
        raise SystemExit(f"QC input is missing required columns: {', '.join(missing)}")

    decisions: list[dict[str, Any]] = []
    gold_records: list[dict[str, Any]] = []
    errors: list[str] = []
    release_ids: set[str] = set()
    agreements = Counter()
    confusion: dict[str, Counter[str]] = defaultdict(Counter)

    for index, row in enumerate(rows, start=2):
        if plain_schema:
            parsed, row_errors = plain_row_labels(row, index)
            if row_errors:
                errors.extend(row_errors)
                continue
            if parsed is None:
                continue
            human_type = parsed["human_type"]
            ai_role = parsed["ai_role"]
            evidence_status = parsed["evidence_status"]
            relationship_patterns = parsed["relationship_patterns"]
            public_signals = parsed["public_signals"]
            distribution_signal = parsed["distribution_signal"]
        else:
            raw_human_type = str(row.get("HUMAN_human_experience_type") or "").strip()
            raw_ai_role = str(row.get("HUMAN_ai_expressive_role") or "").strip()
            raw_evidence_status = str(row.get("HUMAN_evidence_status") or "").strip()
            filled = [bool(raw_human_type), bool(raw_ai_role), bool(raw_evidence_status)]
            if any(filled) and not all(filled):
                errors.append(f"row {index}: complete all three HUMAN label columns or leave all three blank")
                continue
            if not all(filled):
                continue
            human_type = normalize_human_type(raw_human_type)
            ai_role = normalize_ai_role(raw_ai_role)
            evidence_status = normalize_evidence_status(raw_evidence_status)
            relationship_patterns, _ = normalize_relationship_patterns(
                None,
                fallback_configuration=str(row.get("model_configuration") or ""),
            )
            distribution_signal = "not_shown"
            public_signals = {}
        if human_type not in HUMAN_TYPES:
            errors.append(f"row {index}: invalid human type {human_type!r}")
            continue
        if ai_role not in AI_ROLES:
            errors.append(f"row {index}: invalid AI role {ai_role!r}")
            continue
        if evidence_status not in EVIDENCE_STATUSES:
            errors.append(f"row {index}: invalid evidence status {evidence_status!r}")
            continue
        if evidence_status == "insufficient" and not (human_type == "unclear" and ai_role == "unclear"):
            errors.append(
                f"row {index}: evidence_status=insufficient requires HUMAN human=unclear and AI=unclear"
            )
            continue

        release_id = str(row.get("release_id") or "").strip()
        event_id = str(row.get("event_id") or "").strip()
        unit_key = str(row.get("unit_key") or "").strip()
        if not release_id or not event_id or not unit_key:
            errors.append(f"row {index}: release_id, event_id, and unit_key are required")
            continue
        release_ids.add(release_id)

        configuration, human_direction, ai_direction, plain_label = derive_configuration(
            human_type, ai_role, evidence_status
        )
        if not plain_schema:
            relationship_patterns, _ = normalize_relationship_patterns(
                None,
                fallback_configuration=configuration,
            )
            public_signals = public_signals_from_patterns(
                relationship_patterns,
                configuration=configuration,
                human_direction=human_direction,
                evidence_status=evidence_status,
                distribution_signal=distribution_signal,
            )
        one_sided = configuration in {
            "human_enabling_only", "human_constraining_only",
            "ai_enabling_only", "ai_constraining_only",
        }
        if one_sided and evidence_status != "partial":
            errors.append(f"row {index}: one-sided configuration {configuration} requires evidence_status=partial")
            continue
        if evidence_status == "partial" and not one_sided:
            errors.append(f"row {index}: evidence_status=partial requires exactly one directional side and one neutral side")
            continue

        model_human = normalize_human_type(row.get("model_human_experience_type"))
        model_ai = normalize_ai_role(row.get("model_ai_expressive_role"))
        model_evidence = normalize_evidence_status(row.get("model_evidence_status"))
        model_config = str(row.get("model_configuration") or "").strip()
        model_patterns, _ = normalize_relationship_patterns(
            row.get("model_relationship_patterns"),
            fallback_configuration=model_config,
        )
        exact = (human_type, ai_role, evidence_status) == (model_human, model_ai, model_evidence)
        pattern_exact = all(
            bool(relationship_patterns.get(key)) == bool(model_patterns.get(key))
            for key in RELATIONSHIP_PATTERN_KEYS
        )
        if evidence_status == "insufficient":
            review_status = "insufficient_evidence"
        elif exact:
            review_status = "accepted"
        else:
            review_status = "corrected"
        agreements["reviewed"] += 1
        agreements["exact_component_agreement"] += int(exact)
        agreements["configuration_agreement"] += int(configuration == model_config)
        agreements["evidence_status_agreement"] += int(evidence_status == model_evidence)
        agreements["relationship_pattern_agreement"] += int(pattern_exact)
        confusion[model_config][configuration] += 1

        reviewer = str(row.get("HUMAN_reviewer_name") or "").strip() or args.reviewer
        reviewed_at = str(row.get("HUMAN_reviewed_at") or "").strip() or now_iso()
        reasoning = str(row.get("HUMAN_reasoning") or "").strip()
        source_urls = split_pipe(row.get("source_urls"))
        source_headlines = split_pipe(row.get("source_headlines"))
        notes = (
            "Owner quality-control adjudication. "
            + (reasoning if reasoning else "Final component labels supplied by the reviewer.")
        )

        decision_id = f"owner-qc-event-{release_id}-{event_id}-v1"
        final = {
            "human_experience_type": human_type,
            "ai_expressive_role": ai_role,
            "evidence_status": evidence_status,
            "relationship_patterns": relationship_patterns,
            "public_signals": public_signals,
            "distribution_signal": distribution_signal,
            "public_takeaway": reasoning,
            "story_country_iso3s": [],
            "evidence_summary": str(row.get("source_headlines") or row.get("development_title") or "").strip(),
            "reasoning": reasoning,
            "empowerment_status": "unclear",
            "empowerment_degree": 0,
            "empowerment_reasoning": "Owner QC adjudication focused on the relationship codebook; no separate empowerment degree was asserted.",
        }
        decisions.append(
            {
                "decision_id": decision_id,
                "release_id": release_id,
                "lens": "event",
                "unit_key": unit_key,
                "article_id": None,
                "event_id": event_id,
                "review_status": review_status,
                "reviewer_name": reviewer,
                "notes": notes,
                "source_urls": source_urls,
                "final": final,
            }
        )

        if truthy(row.get("HUMAN_include_in_gold")):
            gold_records.append(
                {
                    "gold_id": f"gold:{unit_key}",
                    "release_id": release_id,
                    "lens": "event",
                    "unit_key": unit_key,
                    "event_id": event_id,
                    "title": str(row.get("development_title") or "").strip(),
                    "source_headlines": source_headlines,
                    "source_urls": source_urls,
                    "novelty_status": str(row.get("novelty_status") or "").strip(),
                    "model_at_review": {
                        "configuration": model_config,
                        "human_experience_type": model_human,
                        "ai_expressive_role": model_ai,
                        "evidence_status": model_evidence,
                        "relationship_patterns": model_patterns,
                    },
                    "final": {
                        "configuration": configuration,
                        "plain_label": plain_label,
                        "human_experience_type": human_type,
                        "ai_expressive_role": ai_role,
                        "human_direction": human_direction,
                        "ai_direction": ai_direction,
                        "evidence_status": evidence_status,
                        "relationship_patterns": relationship_patterns,
                        "public_signals": public_signals,
                        "distribution_signal": distribution_signal,
                        "public_takeaway": reasoning,
                    },
                    "reviewer_name": reviewer,
                    "reviewed_at": reviewed_at,
                    "review_reasoning": reasoning,
                    "provenance": "owner_manual_qc",
                }
            )

    if errors:
        for message in errors:
            print(f"ERROR: {message}")
        raise SystemExit(f"QC validation failed with {len(errors)} error(s).")
    if not decisions:
        raise SystemExit("No completed HUMAN rows were found; nothing to ingest.")

    decisions_manifest = {
        "schema_version": "aieo_symbiosis_reviews_v1",
        "codebook_version": CODEBOOK_VERSION,
        "generated_at": now_iso(),
        "reviewer_name": args.reviewer,
        "review_method": "owner_manual_quality_control",
        "review_method_note": (
            "Optional owner QC. Only explicitly completed rows are treated as reviewed; unfilled rows remain unreviewed."
        ),
        "source_release_ids": sorted(release_ids),
        "expected_unit_count": len(decisions),
        "reviewed_unit_count": len(decisions),
        "decisions": decisions,
    }

    gold_path = root_path(args.gold_path)
    gold = load_gold(gold_path)
    existing = {str(row.get("unit_key") or ""): row for row in gold.get("records") or [] if row.get("unit_key")}
    for row in gold_records:
        existing[row["unit_key"]] = row
    merged_records = sorted(existing.values(), key=lambda row: (str(row.get("release_id") or ""), str(row.get("unit_key") or "")))
    gold["updated_at"] = now_iso()
    gold["records"] = merged_records

    reviewed_n = int(agreements["reviewed"])
    batch_material = [
        {
            "unit_key": str(row.get("unit_key") or ""),
            "human_experience_type": str((row.get("final") or {}).get("human_experience_type") or ""),
            "ai_expressive_role": str((row.get("final") or {}).get("ai_expressive_role") or ""),
            "evidence_status": str((row.get("final") or {}).get("evidence_status") or ""),
            "relationship_patterns": (row.get("final") or {}).get("relationship_patterns") or {},
            "distribution_signal": str((row.get("final") or {}).get("distribution_signal") or ""),
        }
        for row in decisions
    ]
    batch_material.sort(key=lambda item: item["unit_key"])
    qc_batch_id = "qc-" + hashlib.sha256(
        json.dumps(batch_material, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:16]
    summary = {
        "schema_version": "aieo_symbiosis_qc_ingest_summary_v1",
        "generated_at": now_iso(),
        "input": str(input_path),
        "release_ids": sorted(release_ids),
        "input_rows": len(rows),
        "reviewed_rows": reviewed_n,
        "gold_rows_from_this_file": len(gold_records),
        "owner_gold_total": len(merged_records),
        "configuration_agreement_rate": (agreements["configuration_agreement"] / reviewed_n) if reviewed_n else None,
        "component_exact_agreement_rate": (agreements["exact_component_agreement"] / reviewed_n) if reviewed_n else None,
        "evidence_status_agreement_rate": (agreements["evidence_status_agreement"] / reviewed_n) if reviewed_n else None,
        "relationship_pattern_agreement_rate": (agreements["relationship_pattern_agreement"] / reviewed_n) if reviewed_n else None,
        "model_to_human_configuration_confusion": {key: dict(value) for key, value in confusion.items()},
        "qc_batch_id": qc_batch_id,
        "dry_run": args.dry_run,
    }

    decisions_path = root_path(args.decisions_output)
    summary_path = root_path(args.summary_output)
    decisions_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    decisions_path.write_text(json.dumps(decisions_manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if not args.dry_run:
        gold_path.parent.mkdir(parents=True, exist_ok=True)
        gold_path.write_text(json.dumps(gold, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

        history_path = root_path(args.history_path)
        if history_path.exists():
            history = json.loads(history_path.read_text(encoding="utf-8"))
        else:
            history = {
                "schema_version": "aieo_symbiosis_owner_qc_history_v1",
                "codebook_version": CODEBOOK_VERSION,
                "description": "Owner-adjudicated optional QC batches and observed model agreement over time.",
                "updated_at": None,
                "batches": [],
            }
        if history.get("codebook_version") != CODEBOOK_VERSION:
            raise SystemExit(
                f"Owner QC history codebook {history.get('codebook_version')} does not match {CODEBOOK_VERSION}."
            )
        batch_record = {
            "qc_batch_id": qc_batch_id,
            "recorded_at": now_iso(),
            "reviewer_name": args.reviewer,
            "release_ids": sorted(release_ids),
            "reviewed_rows": reviewed_n,
            "gold_rows": len(gold_records),
            "configuration_agreement_rate": summary["configuration_agreement_rate"],
            "component_exact_agreement_rate": summary["component_exact_agreement_rate"],
            "evidence_status_agreement_rate": summary["evidence_status_agreement_rate"],
            "relationship_pattern_agreement_rate": summary["relationship_pattern_agreement_rate"],
            "model_to_human_configuration_confusion": summary["model_to_human_configuration_confusion"],
        }
        existing_batches = [
            row for row in (history.get("batches") or [])
            if isinstance(row, dict) and row.get("qc_batch_id") != qc_batch_id
        ]
        existing_batches.append(batch_record)
        existing_batches.sort(key=lambda row: str(row.get("recorded_at") or ""))
        history["updated_at"] = now_iso()
        history["batches"] = existing_batches
        history_path.parent.mkdir(parents=True, exist_ok=True)
        history_path.write_text(json.dumps(history, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
